services:
  ms_graph_docker:
    build: .
    image: graph_docker:local
    container_name: ms_graph_docker
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./token.txt:/app/token.txt
      - ./.env:/app/.env
